server.port=8585
server.servlet.context-path=/workintech

management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health,mappings

info.app.name=Developer Application
info.app.description=Workintech Developer Project
info.app.version=1.0.0